maint: make distcheck pass again
Since commit v4.6.0-67-g595060f, 'make distcheck' failed:

  ERROR: files left in build directory after distclean:
  ./find/oldfindnoop.out
  ./find/findnoop.out
  ./find/find--noop.err
  ./find/oldfind--noop.out
  ./find/find--noop.out
  ./find/oldfind--noop.err
  ./find/findnoop.err
  ./find/oldfindnoop.err
  Makefile:1985: recipe for target 'distcleancheck' failed

* find/testsuite/sv-48180-refuse-noop.sh: Change the names of the *out
and *err files to be located in the temporary directory.