maint: avoid -Werror=unused-macros warning in oldfind
oldfind.c: At top level:
oldfind.c:88:0: error: macro "N_" is not used [-Werror=unused-macros]
 # define N_(String) gettext_noop (String)

cc1: all warnings being treated as errors

* find/oldfind.c (N_): Remove unused macro.