maint: avoid -Werror=missing-prototypes warning in oldfind
oldfind.c:169:1: error: no previous prototype for ‘get_current_dirfd’ [-Werror=missing-prototypes]
 get_current_dirfd (void)
 ^~~~~~~~~~~~~~~~~

* find/oldfind.c (get_current_dirfd): Remove unused function.