build: add -Wno-unused-parameter
The following new warning sneaked in with the gnulib update in the
previous commit:
  In file included from parser.c:49:0:
  ../gl/lib/stat-time.h: In function 'stat_time_normalize':
  ../gl/lib/stat-time.h:215:47: error: unused parameter 'st' \
  [-Werror=unused-parameter]
   stat_time_normalize (int result, struct stat *st)
                                                 ^~

* configure.ac: Add the -Wno-unused-parameter option explicitly as it
is implied - and thus overridden - by the more general -Wunused option.