tests: cleanup files left behind by sv-52220.sh
'make distcheck' failed with:
  ...
  ERROR: files left in build directory after distclean:
  ./find/testsuite/find.err
  ./find/testsuite/oldfind.err
  Makefile:2064: recipe for target 'distcleancheck' failed

* find/testsuite/sv-52220.sh: Add command to remove the temporary
files used for stderr output.

Bug introduced in commit v4.6.0-123-gef1581e.