maint: avoid error from sc_prohibit_gnu_make_extensions
Since last gnulib update, the above syntax-check rule fails:

  Error: doc/Makefile: $< in a non implicit rule
  find_mono.html: find.texi
  ...
  make: *** [maint.mk:439: sc_prohibit_gnu_make_extensions] Error 1

* doc/Makefile.am (find_mono.html): Avoid $< in plain rules.
(findutils.texi_html_node.tar.gz): Likewise.

See also: <https://lists.gnu.org/r/bison-patches/2019-05/msg00017.html>